# Generated by Django 2.1.2 on 2018-11-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=255)),
                ('tweet_name', models.CharField(max_length=255)),
                ('followings', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('favorites_count', models.IntegerField()),
                ('tweets_count', models.IntegerField()),
                ('localisation', models.CharField(max_length=255)),
                ('photo_profile', models.URLField(blank=True, db_index=True, max_length=256, unique=True)),
                ('profile_banner_url', models.URLField(blank=True, db_index=True, max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screen_name', models.CharField(max_length=255)),
                ('tweet_text', models.CharField(max_length=255)),
            ],
        ),
    ]
