# Generated by Django 2.1.2 on 2018-11-16 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='photo_profile',
            field=models.URLField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_banner_url',
            field=models.URLField(blank=True, max_length=256),
        ),
    ]
